config/routes.rb
Rails.application.routes.draw do

  root to: 'buttercms/pages#home'

  scope :module => 'buttercms' do
    get '/categories/:slug' => 'categories#show', :as => :buttercms_category
    get '/author/:slug' => 'authors#show', :as => :buttercms_author

    get '/blog/rss' => 'feeds#rss', :format => 'rss', :as => :buttercms_blog_rss
    get '/blog/atom' => 'feeds#atom', :format => 'atom', :as => :buttercms_blog_atom
    get '/blog/sitemap.xml' => 'feeds#sitemap', :format => 'xml', :as => :buttercms_blog_sitemap

    get '/blog(/page/:page)' => 'posts#index', :defaults => {:page => 1}, :as => :buttercms_blog
    get '/blog/:slug' => 'posts#show', :as => :buttercms_post
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buttercms/authors_controller.rb
class Buttercms::AuthorsController < Buttercms::BaseController
  def show
    @author = ButterCMS::Author.find(params[:slug], :include => :recent_posts)
  end
end

app/controllers/buttercms/base_controller.rb
class Buttercms::BaseController < ActionController::Base
  # You can of course change this layout to your main application layout
  # to have your blog match the rest of your site.
  layout 'buttercms/default'
end

app/controllers/buttercms/categories_controller.rb
class Buttercms::CategoriesController < Buttercms::BaseController
  def show
    @category = ButterCMS::Category.find(params[:slug], :include => :recent_posts)
  end
end

app/controllers/buttercms/feeds_controller.rb
class Buttercms::FeedsController < Buttercms::BaseController
  def sitemap
    feed = ButterCMS::Feed.find(:sitemap)

    render :xml => feed.data
  end

  def atom
    feed = ButterCMS::Feed.find(:atom)

    render :xml => feed.data
  end

  def rss
    feed = ButterCMS::Feed.find(:rss)

    render :xml => feed.data
  end
end

app/controllers/buttercms/pages_controller.rb
class Buttercms::PagesController < ApplicationController

  def home
    
  end
end

app/controllers/buttercms/posts_controller.rb
class Buttercms::PostsController < Buttercms::BaseController
  def index
    @posts = ButterCMS::Post.all(:page => params[:page], :page_size => 10)

    @next_page = @posts.meta.next_page
    @previous_page = @posts.meta.previous_page
  end

  def show
    @post = ButterCMS::Post.find(params[:slug])

    @next_post = @post.meta.next_post
    @previous_post = @post.meta.previous_post
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buttercms/pages_helper.rb
module Buttercms::PagesHelper
end

app/views/buttercms/authors/show.html.erb
<%= content_for :html_title, "#{@author.first_name} #{@author.last_name}" %>
<%= content_for :meta_description, @author.bio %>

<!-- Author name -->
<h2><%= @author.first_name %> <%= @author.last_name %></h2>

<!-- Author profile -->
<% if @author.profile_image %>
  <img src="<%= @author.profile_image %>" />
<% end %>

<p>Title: <%= @author.title %></p>
<p>Bio: <%= @author.bio %></p>

<!-- Recent posts -->
<h4>Recent posts</h4>

<ul>
  <% @author.recent_posts.each do |post| %>
    <li><%= render :partial => 'buttercms/posts/post', :locals => {:post => post} %></li>
  <% end %>
</ul>

app/views/buttercms/categories/show.html.erb
<%= content_for :html_title, @category.name %>

<!-- Category name -->
<h2><%= @category.name %></h2>

<!-- Recent posts -->
<h4>Recent posts</h4>

<ul>
  <% @category.recent_posts.each do |post| %>
    <li><%= render :partial => 'buttercms/posts/post', :locals => {:post => post} %></li>
  <% end %>
</ul>

app/views/buttercms/pages/home.html.erb
<h1>Hi Tomo</h1>
<%= link_to "Check the blog", buttercms_blog_path %>

app/views/buttercms/posts/_post.html.erb
<div>
  <!-- Featured image -->
  <%= image_tag(post.featured_image) if post.featured_image %>

  <!-- Post title -->
  <h4><%= link_to post.title, buttercms_post_path(post.slug), :title => post.title %></h4>

  <!-- Post author -->
  by <%= link_to "#{post.author.first_name} #{post.author.last_name}", buttercms_author_path(post.author.slug) %>

  <!-- Post summary -->
  <p><%= post.summary %></p>

  <!-- Post categories -->
  <% post.categories.each do |category| %>
    <%= link_to category.name, buttercms_category_path(category.slug), :title => category.name %>
  <% end %>
</div>

app/views/buttercms/posts/index.html.erb
<h2>Posts</h2>

<!-- List of posts -->
<% @posts.each do |post| %>
  <%= render :partial => 'post', :locals => {:post => post} %>
<% end %>

<!-- Pagination links -->
<div>
  <% if @previous_page %>
    <%= link_to "Prev", buttercms_blog_path(:page => @previous_page) %>
  <% end %>

  <% if @next_page %>
    <%= link_to "Next", buttercms_blog_path(:page => @next_page) %>
  <% end %>
</div>

app/views/buttercms/posts/show.html.erb
<%= content_for :html_title, @post.seo_title %>
<%= content_for :meta_description, @post.meta_description %>

<!-- Post title -->
<h2><%= @post.title %></h2>

<!-- Post author -->
<p>
  <%= link_to "#{@post.author.first_name} #{@post.author.last_name}", buttercms_author_path(@post.author.slug) %>
</p>

<!-- Post categories -->
<% @post.categories.each do |category| %>
  <%= link_to category.name, buttercms_category_path(category.slug), :title => category.name %>
<% end %>

<!-- Publish date -->
<p><%= Time.parse(@post.published).strftime('%B %d, %Y') %></p>

<!-- Post body -->
<%= @post.body.html_safe %>

<!-- Link to Next Post -->
<% if @next_post %>
  <%= link_to @next_post.title, buttercms_post_path(@next_post.slug), :title => @next_post.title %>
<% end %>

<!-- Link to Previous Post --> 
<% if @previous_post %>
  <%= link_to @previous_post.title, buttercms_post_path(@previous_post.slug), :title => @previous_post.title %>
<% end %>

<!--
// For sharing, we recommend https://www.addthis.com/get/sharing or https://sumome.com/app/share
-->

<!--
// For commenting, we recommend https://disqus.com/
// Create a Disqus account and paste your snippet below

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'XXXXXXXX';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buttertest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/buttercms/default.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= content_for?(:html_title) ? "#{content_for(:html_title)} | My Blog" : "My Blog" %></title>

    <meta name="description" content="<%= content_for?(:meta_description) ? content_for(:meta_description) : "My Blog" %>">

    <link rel="alternate" type="application/atom+xml" title="My Blog - Atom" href="<%= buttercms_blog_atom_path %>">
    <link rel="alternate" type="application/rss+xml" title="My Blog - RSS" href="<%= buttercms_blog_rss_path %>">

    <!-- See https://buttercms.com/docs/#cssstyling -->
    <link rel="stylesheet" href="http://d2z2rr99bkshyr.cloudfront.net/buttercms-post-defaults.css">
</head>
<body>
    <div>
      <%= link_to "Blog home", buttercms_blog_path %>
    </div>

    <%= yield %>
</body>
</html>